# Generated by Django 5.1.3 on 2024-11-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fileapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fileshare",
            unique_together=set(),
        ),
    ]
